### ISSUE TITLE
Text is same color as background in file rename dialogue

### ISSUE THREAD

**Issue by lostatc** [aCluelessDanny/typora-theme-ursine#1]
Hey! I absolutely adore this theme. It's my favorite Typora theme by far.

I've noticed that in Polar, when you rename a file in either the file list view or the tree view, the text is the same color as the dialogue box. This makes the text unreadable while you're renaming the file. In the image below, you can tell that there is text in the box because of the red typo squiggles, but you can't read it.

![CSS Bug](https://user-images.githubusercontent.com/19890498/54066594-8462a000-4200-11e9-9149-29848c87fe62.png)

Thanks again for this great theme!

**Comment by aCluelessDanny** [comment]
Ah, I thought I'd miss something somewhere. I just pushed a couple of changes, so it should be working now with the latest release; tell me if it's working for ya now. And thanks a lot, glad you like the theme!

> _And on an unrelated note, yay, my first issue~. I should probably find the setting to notify me of issues because this slipped right by me, haha_

**Comment by lostatc** [comment]
The file rename dialogue is working for me now. Thanks for the fix! Upon closer inspection, I found a few other cases where the text color is the same as the background color. One is the file search dialogue and the other is the outline filter dialogue. The "Case Sensitive" and "Whole Word" modifiers in the text box are also invisible until you hover over them.

![File Search](https://user-images.githubusercontent.com/19890498/54132113-04982980-43ea-11e9-97cb-9e0eba1379fe.png)
![Outline Filter](https://user-images.githubusercontent.com/19890498/54132122-07931a00-43ea-11e9-9483-bd37102adc4b.png)

Sorry I didn't catch these before!

**Comment by aCluelessDanny** [comment]
Huh, looks like this is a Windows thing. It works fine on Mac, so I didn't catch it at first. Oddly enough, I can't find the option for the outline filtering in Windows, but I *think* that one change I did should fix both issues.
But just in case, mind if you can replace your `ursine-umbra.css` file with this [one](https://github.com/aCluelessDanny/typora-theme-ursine/files/2958395/ursine-umbra.css.zip)? Just to verify it works on your end. If it doesn't, can you tell me the shortcut for that? I can't find it anywhere for some reason, haha

**Comment by lostatc** [comment]
That change fixes both issues on my end. Thanks! To access outline filtering, I hover my mouse over the sidebar while in the outline view and scroll up.
