### ISSUE TITLE
blockquotes left border may not displayed correctly

### ISSUE THREAD

**Issue by idleyui** [aCluelessDanny/typora-theme-ursine#11]
view in ursine:
![image](https://user-images.githubusercontent.com/12003168/56796883-11f85e80-6846-11e9-9f5d-81be2bec7009.png)

I think this might be better( I changed some css ):
![image](https://user-images.githubusercontent.com/12003168/56796954-394f2b80-6846-11e9-9900-d589b77a89eb.png)

my source code
```markdown
>The left border may not displayed correctly when the list and code block is used in blockquotes
>
>- item1
>- item2
>
>```python
>import tensorflow as tf
>```
>
>
```

**Comment by aCluelessDanny** [comment]
Yeah, that does look prettier. I'll look into it once I get through some of my finals here

**Comment by aCluelessDanny** [comment]
The [release](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.6) with the fix is up now! It was a really simple fix really, but I wasn't able to make a new release earlier due to college finals work, so pardon the delay on this
