### ISSUE TITLE
The list numbers may not display correctly.

### ISSUE THREAD

**Issue by PlasmaNeon** [aCluelessDanny/typora-theme-ursine#12]
I downloaded the latest release of Ursine (1.5.1) but it seems that the list numbers are "half chopped". Check the screenshot followed.

![image](https://user-images.githubusercontent.com/24621492/56864577-9c7fc000-69f6-11e9-9382-2a3ad26fc3ca.png)

**Comment by aCluelessDanny** [comment]
I think I found what's causing it & will try to patch that up real quick. Though there's a couple of other things I wanna do before putting out a new release (and final exams have been kicking my butt so far), so I'll comment here again once I put it up

**Comment by PlasmaNeon** [comment]
Also I found that the numbers will display correctly if maximizing Typora window, but that doesn't work every time.

**Comment by aCluelessDanny** [comment]
Yeah, it's kinda finicky. I wasn't able to replicate it for a while, and I only managed to stumble upon it when opening the lorem ipsum file the default kit gives you. At least the solution isn't too hard to implement

**Comment by aCluelessDanny** [comment]
[Release](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.6) with the fix is up now! Sorry it took a while since this issue opened, college got pretty brutal in the last couple of weeks.
