### ISSUE TITLE
help

### ISSUE THREAD

**Issue by PandoraCoCo** [aCluelessDanny/typora-theme-ursine#14]
This theme exports to PDF is different from bear. Could anyone help?

**Comment by aCluelessDanny** [comment]
You might need to be more specific. In what ways is it different? There are a few limitations I've bumped into when exporting to PDF, so maybe you're referring to that

**Comment by PandoraCoCo** [comment]
> You might need to be more specific. In what ways is it different? There are a few limitations I've bumped into when exporting to PDF, so maybe you're referring to that

![image](https://user-images.githubusercontent.com/24877106/58527517-83407e00-8205-11e9-8c43-454f924cacf1.png)

**Comment by aCluelessDanny** [comment]
Ah, it's only the header indicators? I could consider removing those from the export, though I don't see an issue with leaving them there. Bare in mind that Ursine isn't planned to completely imitate Bear's look and feel, but more so take inspiration from it and add some personal touches to it.

With that said, I'm gonna close this, but feel free to suggest anything else about the exported look.

**Comment by PandoraCoCo** [comment]
> Ah, it's only the header indicators? I could consider removing those from the export, though I don't see an issue with leaving them there. Bare in mind that Ursine isn't planned to completely imitate Bear's look and feel, but more so take inspiration from it and add some personal touches to it.
> 
> With that said, I'm gonna close this, but feel free to suggest anything else about the exported look.

Thank you!
I just think PDF should be more formal. It feels a little weird if there are header indicators there.
