### ISSUE TITLE
Preferences page is unreadable

### ISSUE THREAD

**Issue by sushruth** [aCluelessDanny/typora-theme-ursine#2]
Background and text do not have readable contrast.

![image](https://user-images.githubusercontent.com/2114206/54222624-024dd200-44b3-11e9-82d0-92b535d802a8.png)

**Comment by aCluelessDanny** [comment]
Yeah, I haven't been able to style any of the unibody elements yet (like that preferences page), since this was only tested on MacOS up until now. I should be able to put up some Windows-related styling up soon enough

**Comment by aCluelessDanny** [comment]
Just pushed some changes, & it should look alright now. [Give it a try](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.2) and feel free to point out anything off
