### ISSUE TITLE
Missing font Cousine-Regular.woff in release package

### ISSUE THREAD

**Issue by krokofant** [aCluelessDanny/typora-theme-ursine#20]
The font is not included in the release but used in the styles

**Comment by aCluelessDanny** [comment]
Yikes, well that's a bad mistake I left unresolved for...like 3 weeks.

Sorry for the long wait, I've been out of town, & I forgot to check back on these issues after getting back. Much appreciated for the PR (and for the other two as well, I'm looking into them now). I merged it into the dev branch so I can get it ready along with the other fixes.

I'm gonna try and get a release out before daylight's gone, so off I go
