### ISSUE TITLE
Ursine Polar dark shadow over text

### ISSUE THREAD

**Issue by cemetary** [aCluelessDanny/typora-theme-ursine#27]
Hi there.

I found a bug in Settings and dialogs tab. See images below.

Typora version: `0.9.73`
Ursine version: `1.6.3`
Tested in Linux and Windows 10

![Captura realizada el 2019-08-07 09 21 24](https://user-images.githubusercontent.com/10538213/62636660-78067e80-b929-11e9-9f5b-ece7c5c08bef.png) ![Captura realizada el 2019-08-07 09 21 42](https://user-images.githubusercontent.com/10538213/62636662-789f1500-b929-11e9-8a14-bf744b6eb45a.png) ![Peek 07-08-2019 09-32](https://user-images.githubusercontent.com/10538213/62636669-7e94f600-b929-11e9-8f16-50d948ac0979.gif) ![Peek 07-08-2019 09-47](https://user-images.githubusercontent.com/10538213/62637338-ca946a80-b92a-11e9-9d0a-6b483f240749.gif)

Thank you.

**Comment by aCluelessDanny** [comment]
Ah, that's the new preferences window. Doesn't affect Mac, but looks like Windows & Linux needs some styling. I'm gonna get right on it when I can
