### ISSUE TITLE
The border of denoted code vanishes when in the table (Umbra, Mac OS)

### ISSUE THREAD

**Issue by Konfido** [aCluelessDanny/typora-theme-ursine#29]
The color of the border needs to be adjusted a little.

![](https://user-images.githubusercontent.com/25447610/62833087-67c50b00-bc6b-11e9-9471-903ac1259f7d.png)

**Comment by aCluelessDanny** [comment]
Mm yeah, I'll try to get on that when I can. Probably best if I go for a somewhat translucent white rather than a solid color
