### ISSUE TITLE
Sidebar "code" text disappears

### ISSUE THREAD

**Issue by reparke** [aCluelessDanny/typora-theme-ursine#30]
In UrsinePolar, when `code` is used in a title, it is white on white in the bar.

Markdown
`## Setting input / output with pinMode `
(not "pinMode" is in code formatting)

Example
![image](https://user-images.githubusercontent.com/11014413/62982848-59e5c600-bde2-11e9-9726-cedc7a4559e4.png)

**Comment by aCluelessDanny** [comment]
Ursine Polar always has a trick up its sleeve, haha. I'll get on that after fixing a couple of other issues here and there
