### ISSUE TITLE
How can I change it back?I don't like the new color

### ISSUE THREAD

**Issue by danielduyixin** [aCluelessDanny/typora-theme-ursine#36]
Ah yes! I recently changed the highlighter color for both themes in [1.6.3](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.6.3), I just haven't updated the screenshots in the README yet, ahah. But that is the intended color (though I might change them again since I think the color could stand out a bit more as a highlighter).

And thank you, glad you like it!

_Originally posted by @aCluelessDanny in https://github.com/aCluelessDanny/typora-theme-ursine/issues/34#issuecomment-526349911_

**Comment by aCluelessDanny** [comment]
Oh it's pretty much the same way as I mentioned [here](https://github.com/aCluelessDanny/typora-theme-ursine/issues/35#issuecomment-526670111), though you'd want to change the `$mark-color` variable in the `.scss` files or the `background` property in the `mark` rule directly in either the `.scss` or `.css` files.
