### ISSUE TITLE
Diagram background color causes text to be unreadable (Umbra, Linux)

### ISSUE THREAD

**Issue by Prometheus625** [aCluelessDanny/typora-theme-ursine#38]
![image](https://user-images.githubusercontent.com/21979988/66156900-77136580-e5d7-11e9-9edf-76d0d99d86f2.png)

**Comment by krokofant** [comment]
@Prometheus625 Are there more graph scenarios that look weird? Would be great to have a few more test cases.

**Comment by Prometheus625** [comment]
The flowchart using flowchart.js and the sequence diagram using js-sequence both look normal. It's the mermaid charts that are strange.

Here's the example sequence diagram using mermaid:
 ![image](https://user-images.githubusercontent.com/21979988/66221635-44737680-e684-11e9-9db9-6e4adc37295b.png)

Graph using mermaid:
![image](https://user-images.githubusercontent.com/21979988/66221699-6f5dca80-e684-11e9-9052-08f04002dadc.png)

Gantt using mermaid:
![image](https://user-images.githubusercontent.com/21979988/66221740-82709a80-e684-11e9-8928-534599b52c91.png)

I don't know much about CSS but was able to find that changing `--node-fill` fixed the problem. Adding `--node-fill:#1e2022;` to urisine-umbra.css in :root{} worked.

Here's the mermaid flowchart after:
![image](https://user-images.githubusercontent.com/21979988/66223180-b5685d80-e687-11e9-8b8f-e2f24859ef61.png)

**Comment by aCluelessDanny** [comment]
Huh that's interesting. Looks like Typora uses mermaid's hardcoded, default colors. A few extra CSS rules and a bit of tinkering with those root variables oughta do the trick
<img width="657" alt="image" src="https://user-images.githubusercontent.com/21282515/66261200-a3bdad80-e78e-11e9-91d9-c98bc8aa495c.png">

**Comment by aCluelessDanny** [comment]
And Gantt diagrams should look a lot better now once I get a release up
<img width="655" alt="image" src="https://user-images.githubusercontent.com/21282515/66265863-e8733400-e7e2-11e9-9ef5-7a99733cf263.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/21282515/66265877-0d67a700-e7e3-11e9-86db-d4fdfccea422.png">
