### ISSUE TITLE
Vague View on Scrolling Content in Day Mode

### ISSUE THREAD

**Issue by yif-li** [aCluelessDanny/typora-theme-ursine#42]
Everything is cool expect the vague view on scrolling content in day mode. When scrolling the content on the top-right corner within the document, the shade by cursor is so dark that I cannot see the characters. The function in dark mode works fine, though.

[Example Image](https://i.imgur.com/2Vi74jH.jpg)

**Comment by aCluelessDanny** [comment]
Dang, Polar always has something up its sleeve. Is this from the Windows version of Typora? I don't think I've seen that view before, but that may be because I'm on MacOS

**Comment by krokofant** [comment]
I'm trying to find that view on Windows in the latest Typora build but I can't find it. Not sure what _day mode_ is. 😮

**Comment by aCluelessDanny** [comment]
I think he's referring to Ursine Polar as the "day mode". Though I can't find that view on Windows either.

@YvanYifeiLi How did you enable that Outline view and on which platform are you using Typora on?

**Comment by YvanYifeiLi** [comment]
My bad, I should make it clear. 

Yes, *day mode*  is actually *Ursine Polar* @krokofant.

My system is also MacOS (Catalina) @aCluelessDanny.

 As you can see, when I [click the outline popover](https://i.imgur.com/taw1G9l.jpg), the pop-out within Ursine Polar is [vague](https://i.imgur.com/ly1eo36.jpg), but within Ursine Umbra, it's [fine](https://i.imgur.com/oHEcGP5.jpg).

**Comment by aCluelessDanny** [comment]
So I forgot to push up those fixes a while over the end of the semester and year, but the release is up with the fixes~

Sorry bout that 💦
