### ISSUE TITLE
Change the line feed gap

### ISSUE THREAD

**Issue by Mara-Li** [aCluelessDanny/typora-theme-ursine#46]
Hello !
Quick question about the theme x). I really didn't love line feed gap, so i want change it for have no espace between my line when I do enter (so I must use "two jump" for have a blank line). How can i change that in the theme ?

Thanks for you response !

**Comment by aCluelessDanny** [comment]
Hi there, I'm not sure what exactly you mean by "line feed gap". Is that the space between paragraphs when you press Enter?

**Comment by Mara-Li** [comment]
Yeap !

**Comment by aCluelessDanny** [comment]
Well if it's only paragraphs, you can have add a small rule at the bottom of the css file that goes like so:
```css
#write p + p {
	margin: 0;
}
```
This'll take off the vertical spacing between paragraphs, or you can tweak it the value to your liking (the default value the theme uses is `margin: 0.5rem 0`)

**Comment by Mara-Li** [comment]
Thanks !

**Comment by aCluelessDanny** [comment]
Mmm, try changing the rule to:
```css
#write p {
	margin: 0;
}
```

I think that does better in hindsight. This is what I can get if I use that:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/21282515/74059633-0679bc80-49ae-11ea-9fa7-503d4c6da8af.png">

**Comment by Mara-Li** [comment]
Okay ! Thanks you so much for your help ! Your theme is so good btw x)

**Comment by aCluelessDanny** [comment]
Thank you and no prob! Glad to be of help!~
