### ISSUE TITLE
highlight colors in dark theme

### ISSUE THREAD

**Issue by sugry** [aCluelessDanny/typora-theme-ursine#47]
In the dark  `ursine-umbra-cyrillic.css` you have a problem with highlighting text in code mode. Highlight and text are white and unreadable. A similar problem is with the footer button.
To fix this, I suggest this.

add to section `:root {`
```
:root {
    --select-text-bg-color: #0662D3;
    ...
```
in code from line 909 and below
```
.dropdown-menu .active a,
.dropdown-menu .has-extra-menu.active a,
.dropdown-menu .has-btn-submenu .menu-style-btn.active, #footer-word-count-info .ty-footer-word-count-all tr:hover,
#ty-spell-check-dict-missing-menu li:hover, .ty-spell-check-panel-item.ty-active, .ty-spell-check-panel-item:hover, .footer-item:hover {
  background: #2b2b2b !important;
  color: #ddd !important;
}
```
swap values of variables `background` and `color` as shown here

and add below block e.g.:
```
.footer-item {
  background: #1E2022 !important;
  color: #DEDEDE !important;
}
```

**Comment by aCluelessDanny** [comment]
Gotcha, I should get a few changes up soon. That footer always caused me problems to style, but I think I managed to find a way to get it right. Also the dropdowns are gonna look a bit different since the white highlight on the selected options are a bit much.

**Comment by sugry** [comment]
Thank you, I really like your theme. I wish you to bring it to perfection :)

**Comment by aCluelessDanny** [comment]
Alright, that should patch things up. Check out the latest release and see how it looks~

**Comment by sugry** [comment]
Everything looks good in the latest release. But I see you added a footer border. This is on line 1007
```
footer.ty-footer {
  border-top: 1px solid black;
}
```
Are you sure this is a good design decision? It seems to me that in the previous release it looked better.
```
footer.ty-footer {
  border-top: 0;
}
```
However, this is a matter of taste :)

**Comment by aCluelessDanny** [comment]
Ay, actually I left that there so I can have a visual on the footer so I could later remove it. I forgot to take it off, ahah. It probably doesn't look nice on the Polar version too, so lemme take that off

**Comment by aCluelessDanny** [comment]
There we go, that should do the trick

**Comment by sugry** [comment]
Now all is well. Thanks
