### ISSUE TITLE
Text hard to read in command palette (Ctrl+P)

### ISSUE THREAD

**Issue by moritzge** [aCluelessDanny/typora-theme-ursine#48]
Hi,

When using the light theme (Ursine Polar), it's hard to read the text in the command palette:

![image](https://user-images.githubusercontent.com/2479609/75960407-4904bb00-5ec0-11ea-88fc-32670ea9f7c1.png)

I'm using v1.9.1
It's fine for Ursine Umbra. 

Thanks for this great theme!
Moritz

**Comment by aCluelessDanny** [comment]
Ah God bless, I keep forgetting about the window. I'll get that patched up

**Comment by aCluelessDanny** [comment]
Pardon the delay but the 2.0 release should fix this now~
