### ISSUE TITLE
Buttons in the settings section

### ISSUE THREAD

**Issue by sugry** [aCluelessDanny/typora-theme-ursine#50]
In a dark design theme, when you hover over the button, the background of the button turns white and the button text is not read.
This can be fixed if in the code block starting at line 1160
```
.ty-preferences .btn-default:hover {
  border-color: #428bca;
  background: #2e2e2e;
  color: #fff;
}
```
Change background setting to
```
  background: #2e2e2e !important;
```

**Comment by aCluelessDanny** [comment]
Ah those pesky preference windows. I work primarily in a MacOS environment, so I occasionally miss these. I'll get this patched up in a bit

**Comment by aCluelessDanny** [comment]
Buttons should now have the right colors upon hover in the 2.0 release~
