### ISSUE TITLE
there is nearly no difference between CHOSEN and UNCHOSEN parts

### ISSUE THREAD

**Issue by unbadfish** [aCluelessDanny/typora-theme-ursine#55]
![截图_2020-05-09_20-43-16](https://user-images.githubusercontent.com/61961263/81474213-6ba3af00-9236-11ea-957f-57e8551b7b08.png)

**Comment by aCluelessDanny** [comment]
Pardon the _really_ late reply, but I made a slight coloring change to fix this bit. Should be able to get a quick release out today
