### ISSUE TITLE
Shortcut Headline problem

### ISSUE THREAD

**Issue by Qrizzz** [aCluelessDanny/typora-theme-ursine#56]
I use the shortcuts <kbd>⌘</kbd> + <kbd>1</kbd>…<kbd>6</kbd> to create a headline. When I do this before entering text the Ursine theme somehow moves the hashtags for the headline a line below or above the cursor input.

It’s hard to explain. Here are some screenshots before hitting the shortcut and after (left side normal view, right side source code view).

![before](https://user-images.githubusercontent.com/554443/83155755-db081280-a101-11ea-84b3-db3aeaa6aaf8.jpg)
![after](https://user-images.githubusercontent.com/554443/83155776-e0655d00-a101-11ea-984a-1124a357284e.jpg)

I have no clue why this is happening or if it’s just me. Other themes seem to have no problem.

**Comment by Konfido** [comment]
Same here.

**Comment by aCluelessDanny** [comment]
(Pardon the late reply, college semester got real busy this time around)

But it's also happening on my end, but I honestly have no idea what might be causing it. It's definitely the theme, because every other theme works fine with me. How odd that a stylesheet is causing this...

**Comment by Qrizzz** [comment]
I think it is due to the `position: absolute` in `h1::before` ([Line 423](https://github.com/aCluelessDanny/typora-theme-ursine/blob/42c2815b1385300312fa922c2c2836b05dbefed3/ursine-umbra.scss#L423))

I had a look at some other Themes that outdent the headline information. They use `::before` pseudo-element and negative margin. I managed to change it in the the generated css for myself. I am sure you had something in mind with the absolute position and I don’t know for sure if my “solution” does not break anything else.

**Comment by aCluelessDanny** [comment]
Yeah, it was that! I think back then I had an unorthodox way of styling that part, which is why I used `::after`; but I forgot about it afterwards. Konfido's PR was enough to fix things and it'll be up in the next release once I get things together
