### ISSUE TITLE
code fences issues

### ISSUE THREAD

**Issue by Ypixel** [aCluelessDanny/typora-theme-ursine#6]
hi, when I use the code fences ,in the raw mode ,after that every raw will be fences.like this:
![](https://ws4.sinaimg.cn/large/006tKfTcly1g1e63mh1f7j311w0hm0xz.jpg)

**Comment by aCluelessDanny** [comment]
Just pushed a commit (f8b1817a5ae9c59af6607d9daec0d1e39de93ba1) to fix this. I should be able to get a new release up and ready tomorrow or the day after

**Comment by aCluelessDanny** [comment]
[Release is up](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.4), so this should resolve the issue~

**Comment by Ypixel** [comment]
thanks:)
