### ISSUE TITLE
Almost unreadable text in quick open dialogue

### ISSUE THREAD

**Issue by mbturan** [aCluelessDanny/typora-theme-ursine#7]
Hey, thank you for the nice theme.

Here is a little issue I have in both unibody and native mode in win10. The quick open thingy is almost unreadable. This is Ursine Polar.

![image](https://user-images.githubusercontent.com/18573615/56083263-2e020600-5e2b-11e9-9f0f-abda9de2e1fe.png)

**Comment by aCluelessDanny** [comment]
Sorry for the late response, spring breaks are nice 💦

I completely forgot about that window when I was styling Ursine Polar. I put up a quick fix in the `dev` branch for now (eef5e0e2ff454669f0e5badad3b0a6adc90f2159), but I'll probably style this window a bit before putting together a new release in the next couple of days

**Comment by aCluelessDanny** [comment]
[Release](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.5) is up, so I'll close this up. Do feel free to comment any more issues you bump into
