### ISSUE TITLE
Cannot change font size

### ISSUE THREAD

**Issue by xingeji** [aCluelessDanny/typora-theme-ursine#8]
In preferences panel, Appearance - Font Size - Customized only changes the font size of inline code, not the general text.

**Comment by aCluelessDanny** [comment]
Huh, don't know how that slipped right through me. Just pushed a change to the `dev` branch to fix just that (2e02c21c027ea357e07632e8df07693dc4af0e97), and I'll put together a new release in the next day or two

**Comment by aCluelessDanny** [comment]
Just uploaded the newest [release](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.5), so the text should resize correctly now. Gonna close this if there's no further issues
