### ISSUE TITLE
how to change default focus mode in  Code Blocks 

### ISSUE THREAD

**Issue by zeptolee** [aCluelessDanny/typora-theme-ursine#9]
![image](https://user-images.githubusercontent.com/6327633/56401071-b3e9db00-6289-11e9-975a-15e5a29c1543.png)
When using Code Blocks ， it always show up a default focused line. how to erase it?

**Comment by aCluelessDanny** [comment]
Just pushed a couple of changes to the `dev` branch (most notably 83428ac3e0f01af9f39b1cd3572f813fdaae4c24), & it should be fixed now. I'm gonna put together a new release with some fixes tomorrow or the day after~

<img width="677" alt="image" src="https://user-images.githubusercontent.com/21282515/56553241-6accac00-6553-11e9-8698-26bc2309abc9.png">

**Comment by aCluelessDanny** [comment]
Closing this as the new [release](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.5) is up. Hopefully there aren't any more issues
